name: fortuna_libya_customer
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil:
  flutter_svg:
  provider:
  shared_preferences:
  dio:
  string_validator:  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/icon/

  fonts:
   - family: Dubai
     fonts:
       - asset: fonts/Dubai-Bold.ttf
         weight: 700
       - asset: fonts/Dubai-Medium.ttf
         weight: 500
       - asset: fonts/Dubai-Regular.ttf
         weight: 400
       - asset: fonts/Dubai-Light.ttf
         weight: 300
